web:
  build: ./env/containers/apache/
  ports:
   - "80:80"
   - "9000:9000"
  volumes:
   - .:/var/www/html
  links:
      - redis
  environment:
      - REDIS_PORT=6379
redis:
  build: ./env/containers/redis/
  ports:
    - "6379:6379"
collect:
  build: ./env/containers/php-cli/
  ports:
    - "9001:9000"
  volumes_from:
    - web





